import { CoordinatePoint, Parcel, ProjectMetadata } from '../types';
import { computeParcel, computeExtents } from '../cogo';

/**
 * Generates an AutoCAD Script (.SCR) file that precisely automates the creation of
 * cadastral layout plans, grid lines, boundary polylines, beacon markers, and text labels.
 * 100% syntactically compatible with legacy SurvPack 3.0 scripts.
 */
export function generateAutoCADScript(
  project: ProjectMetadata,
  points: CoordinatePoint[],
  parcels: Parcel[]
): string {
  const extents = computeExtents(points);
  const buffer = Math.max(20, extents.width * 0.1);
  const minE = Math.floor(extents.minX - buffer);
  const maxE = Math.ceil(extents.maxX + buffer);
  const minN = Math.floor(extents.minY - buffer);
  const maxN = Math.ceil(extents.maxY + buffer);

  const lines: string[] = [];

  // Header & Environment Setup
  lines.push('; ==========================================================');
  lines.push(`; AutoCAD Script generated by NSurvey (SurvPack NextGen)`);
  lines.push(`; Project: ${project.code} - ${project.title}`);
  lines.push(`; Location: ${project.location}`);
  lines.push(`; Date: ${project.date} | Surveyor: ${project.surveyorName}`);
  lines.push('; ==========================================================');
  lines.push('');
  lines.push('UNITS 2 2 5 0 N Y');
  lines.push('SETVAR PDMODE 32');
  lines.push('SETVAR REMEMBERFOLDERS 0');
  lines.push('SETVAR PDSIZE 0.5');
  lines.push(`LIMITS ${minE},${minN} ${maxE},${maxN}`);
  lines.push('STYLE STANDARD ARIAL 0 1');
  lines.push('ZOOM E');
  lines.push('');

  // 1. Grid Crosses Layer
  lines.push('; --- Geodetic Grid Crosses Layer ---');
  lines.push('LAYER M modelGridcrosses C 7 ');
  const gridStep = 50; // 50m standard survey grid
  const startGridE = Math.floor(minE / gridStep) * gridStep;
  const startGridN = Math.floor(minN / gridStep) * gridStep;

  for (let e = startGridE; e <= maxE; e += gridStep) {
    for (let n = startGridN; n <= maxN; n += gridStep) {
      lines.push(`POINT ${e},${n}`);
      lines.push(`LINE ${e - 2},${n} ${e + 2},${n} `);
      lines.push(`LINE ${e},${n - 2} ${e},${n + 2} `);
    }
  }
  lines.push('');

  // 2. Beacons Layer
  lines.push('; --- Survey Beacons Layer ---');
  lines.push('LAYER M BEACONS C 1 ');
  for (const pt of points) {
    lines.push(`POINT ${pt.easting.toFixed(3)},${pt.northing.toFixed(3)}`);
  }
  lines.push('');

  // 3. Annotations Layer (Beacon IDs & Coordinates)
  lines.push('; --- Beacon Annotations Layer ---');
  lines.push('LAYER M ANNOTATIONS C 3 ');
  for (const pt of points) {
    // Bottom-Center text offset by 1m
    lines.push(`TEXT J BC ${pt.easting.toFixed(3)},${(pt.northing + 1.0).toFixed(3)} 1.2 0 ${pt.id}`);
  }
  lines.push('');

  // 4. Parcel Boundaries Layer
  lines.push('; --- Parcel Boundaries Layer ---');
  lines.push('LAYER M BOUNDARY C 2 ');
  for (const parcel of parcels) {
    const comp = computeParcel(parcel, points);
    if (!comp || comp.vertices.length < 3) continue;

    const coordsStr = comp.vertices.map(v => `${v.easting.toFixed(3)},${v.northing.toFixed(3)}`).join(' ');
    lines.push(`PLINE ${coordsStr} C`);

    // Plot Centroid Label & Owner Info
    const centE = comp.vertices.reduce((s, v) => s + v.easting, 0) / comp.vertices.length;
    const centN = comp.vertices.reduce((s, v) => s + v.northing, 0) / comp.vertices.length;

    lines.push(`TEXT J MC ${centE.toFixed(3)},${centN.toFixed(3)} 2.0 0 ${parcel.plotNumber}`);
    if (parcel.ownerName) {
      lines.push(`TEXT J MC ${centE.toFixed(3)},${(centN - 2.5).toFixed(3)} 1.4 0 ${parcel.ownerName}`);
    }
    lines.push(`TEXT J MC ${centE.toFixed(3)},${(centN - 4.5).toFixed(3)} 1.2 0 Area: ${comp.areaSquareMeters.toFixed(2)} sq.m`);
  }

  lines.push('');
  lines.push('ZOOM E');
  lines.push('; --- End of Script ---');

  return lines.join('\r\n');
}

/**
 * Generates an AutoCAD Script (.SCR) for an individual parcel or custom subset of parcels.
 */
export function generateParcelsSCR(
  project: ProjectMetadata,
  points: CoordinatePoint[],
  targetParcels: Parcel[]
): string {
  const pointMap = new Map(points.map(p => [p.id, p]));
  const ptIdSet = new Set<string>();
  targetParcels.forEach(p => p.pointIds.forEach(id => ptIdSet.add(id)));
  const relevantPoints = Array.from(ptIdSet).map(id => pointMap.get(id)).filter(Boolean) as CoordinatePoint[];

  const titleSuffix = targetParcels.length === 1 ? targetParcels[0].plotNumber : `${targetParcels.length}_PLOTS`;
  return generateAutoCADScript(
    { ...project, title: `${project.title || 'CAD'} - ${titleSuffix}` },
    relevantPoints,
    targetParcels
  );
}
